
project_id = "zzykyjvjchocuxtxfvok"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
# Enable connection pooling for better performance
pool_size = 15
max_client_conn = 100

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
s3_region = "us-east-1"

[auth]
enabled = true
port = 54328
# Improved auth configuration
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://your-domain.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[functions.deepseek-mcp]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.paypal-payment]
verify_jwt = false

[functions.paypal-capture]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54329

[[edge-runtime.ip_version]]
ip_version = 4

[analytics]
enabled = false
