
project_id = "zzykyjvjchocuxtxfvok"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = 4

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
  
[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://zzykyjvjchocuxtxfvok.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_users = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.paypal-payment]
verify_jwt = true

[functions.paypal-capture]  
verify_jwt = true

[functions.translate]
verify_jwt = false

[functions.deepseek-mcp]
verify_jwt = false
