// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzykyjvjchocuxtxfvok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6eWt5anZqY2hvY3V4dHhmdm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NjE1NDAsImV4cCI6MjA2OTEzNzU0MH0.HmqppN32EAFraAiww4Y5oh9wzkXU4Px9FPPXsZtN6Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});