
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzlhzajmxprhyrmrqxir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6bGh6YWpteHByaHlybXJxeGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTI4MzYsImV4cCI6MjA2OTk4ODgzNn0.s5lHWMEToMdHnL5twcttQCQJRVR2rEwhPKoRu9P9hTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
